"""Render ``docs/encoders/reference.md`` from the encoder descriptors.

Every fact on that page - option labels, defaults, ranges, choices, supported channel
layouts, which common controls an adapter honours - already exists as structured data on
``EncoderDescriptor`` and ``OptionDefinition``. Writing it out by hand means the docs are
wrong the first time an adapter changes, so the page is generated and CI runs this with
``--check`` the same way it runs ``ruff format --check``.

``ffmpeg_audio_encoder.encoders`` and ``.domain`` import no Qt, so this stays headless.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ffmpeg_audio_encoder.domain.models import (
    EncoderDescriptor,
    EncoderGroup,
    JsonScalar,
    OptionDefinition,
    OptionKind,
)
from ffmpeg_audio_encoder.encoders import default_registry

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = PROJECT_ROOT / "docs" / "encoders" / "reference.md"

HEADER = """<!--
Generated by tools/generate_encoder_reference.py - do not edit by hand.
Change the encoder descriptors instead, then re-run the generator.
-->

# Encoder reference

Every encoder the application offers, with the exact options it exposes. This page is
generated from the encoder descriptors in the source tree, so it always matches the
version of the application it ships with.

Options appear under the label the interface uses. The value shown as the default is what
a fresh configuration starts from; presets and the restored last-used configuration
override it.
"""

TOOL_LABELS = {
    "ffmpeg": "FFmpeg",
    "ffprobe": "ffprobe",
    "opusenc": "opusenc",
    "qaac": "qaac",
    "fdkaac": "fdkaac",
    "deezy": "DeeZy",
    "dee": "Dolby Encoding Engine",
    "truehdd": "TrueHDD",
}

KIND_LABELS = {
    OptionKind.INTEGER: "Integer",
    OptionKind.DECIMAL: "Decimal",
    OptionKind.CHOICE: "Choice",
    OptionKind.TEXT: "Text",
    OptionKind.BOOLEAN: "Yes/no",
}

GROUP_INTROS = {
    EncoderGroup.FFMPEG: (
        "Encoders built into FFmpeg itself. They need nothing beyond a working FFmpeg "
        "build, and each is offered only when the configured FFmpeg exposes both the "
        "encoder and the muxer it writes through."
    ),
    EncoderGroup.STANDALONE: (
        "Third-party command-line encoders. FFmpeg decodes the selected source stream to "
        "PCM over a pipe and the external encoder writes the result straight to the "
        "queue's temporary output, so cancellation and atomic publishing behave exactly "
        "as they do for the built-in encoders."
    ),
    EncoderGroup.DEEZY: (
        "Licensed Dolby encoding through DeeZy. These need DeeZy and the Dolby Encoding "
        "Engine, and the Atmos and AC-4 adapters additionally need TrueHDD. See "
        "[DeeZy encoders](deezy.md) for how the adapters behave beyond their options."
    ),
}


def _escape(text: str) -> str:
    """Keep table cells from breaking the surrounding pipe table."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _format_scalar(value: JsonScalar, suffix: str = "") -> str:
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if value is None or value == "":
        return "-"
    return f"{value}{suffix}"


def _format_number(value: float) -> str:
    return str(int(value)) if value == int(value) else str(value)


def _format_sample_rate(rate: int) -> str:
    """44100 renders as 44.1 kHz, not the 44 kHz integer division would give."""
    return f"{_format_number(rate / 1000)} kHz"


def _format_default(option: OptionDefinition) -> str:
    if option.kind is OptionKind.CHOICE:
        for choice in option.choices:
            if choice.value == option.default:
                return f"`{_escape(choice.label)}`"
    formatted = _format_scalar(option.default, option.suffix)
    return formatted if formatted == "-" else f"`{_escape(formatted)}`"


def _format_range(option: OptionDefinition) -> str:
    if option.minimum is None or option.maximum is None:
        return "-"
    low = _format_number(option.minimum)
    high = _format_number(option.maximum)
    return f"{low} to {high}{option.suffix}"


def _format_choices(option: OptionDefinition) -> str:
    if not option.choices:
        return "-"
    return ", ".join(f"`{_escape(choice.label)}`" for choice in option.choices)


def _format_notes(option: OptionDefinition) -> str:
    notes: list[str] = []
    if option.tooltip:
        notes.append(_escape(option.tooltip))
    if option.enabled_when_key:
        values = ", ".join(f"`{_format_scalar(value)}`" for value in option.enabled_when_values)
        notes.append(f"Applies only when *{option.enabled_when_key}* is {values}.")
    elif option.enabled_when_all:
        notes.append("Applies only to some configurations.")
    return " ".join(notes) if notes else "-"


def _requirements(descriptor: EncoderDescriptor) -> str:
    return ", ".join(TOOL_LABELS.get(tool, tool) for tool in descriptor.required_tools)


def _common_controls(descriptor: EncoderDescriptor) -> str:
    supported = {
        "sample rate": descriptor.supports_sample_rate,
        "channel layout": descriptor.supports_channel_layout,
        "gain": descriptor.supports_gain,
        "tempo": descriptor.supports_tempo,
        "delay": descriptor.supports_delay,
    }
    available = [name for name, ok in supported.items() if ok]
    unavailable = [name for name, ok in supported.items() if not ok]
    if not unavailable:
        return "All common audio controls apply."
    if not available:
        return "No common audio controls apply."
    return (
        f"Common audio controls: {', '.join(available)}. Not available: {', '.join(unavailable)}."
    )


def _render_option_table(descriptor: EncoderDescriptor) -> list[str]:
    if not descriptor.options:
        return ["This encoder exposes no adapter-specific options.", ""]
    lines = [
        "| Option | Type | Default | Range | Choices | Notes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for option in descriptor.options:
        cells = (
            _escape(option.label),
            KIND_LABELS[option.kind],
            _format_default(option),
            _format_range(option),
            _format_choices(option),
            _format_notes(option),
        )
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def _render_descriptor(descriptor: EncoderDescriptor) -> list[str]:
    lines = [f"### {descriptor.display_name}", "", f"`{descriptor.id}`", ""]
    lines.append("| | |")
    lines.append("| --- | --- |")
    lines.append("| Codec | " + ", ".join(str(codec) for codec in descriptor.codecs) + " |")
    outputs = ", ".join(
        f"{output_format.value} (`{output_format.suffix}`)"
        for output_format in descriptor.output_formats
    )
    lines.append(f"| Output | {outputs} |")
    lines.append(f"| Requires | {_requirements(descriptor)} |")
    if descriptor.channel_layouts:
        layouts = ", ".join(f"`{_escape(layout.label)}`" for layout in descriptor.channel_layouts)
        lines.append(
            f"| Channel layouts | `{descriptor.default_channel_layout_label}`, {layouts} |"
        )
    if descriptor.sample_rate_choices:
        rates = ", ".join(_format_sample_rate(rate) for rate in descriptor.sample_rate_choices)
        lines.append(f"| Sample rates | `Source`, {rates} |")
    elif descriptor.sample_rate_range is not None:
        low, high = descriptor.sample_rate_range
        lines.append(f"| Sample rates | `Source`, {low} Hz to {high} Hz |")
    lines.append("")
    lines.append(_common_controls(descriptor))
    lines.append("")
    lines.extend(_render_option_table(descriptor))
    return lines


def render() -> str:
    grouped: dict[EncoderGroup, list[EncoderDescriptor]] = {}
    for adapter in default_registry():
        grouped.setdefault(adapter.descriptor.group, []).append(adapter.descriptor)

    lines = [HEADER.rstrip("\n"), ""]
    for group in EncoderGroup:
        descriptors = grouped.get(group)
        if not descriptors:
            continue
        lines.extend([f"## {group.value}", "", GROUP_INTROS[group], ""])
        for descriptor in descriptors:
            lines.extend(_render_descriptor(descriptor))
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(prog="generate_encoder_reference")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the committed page is out of date",
    )
    arguments = parser.parse_args()

    rendered = render()
    relative = OUTPUT_PATH.relative_to(PROJECT_ROOT).as_posix()
    if arguments.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if current == rendered:
            return 0
        print(
            f"{relative} is out of date. Run: uv run python tools/generate_encoder_reference.py",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
